### PR TITLE
Fix enterprise github auth

### PR DESCRIPTION
**Pull request by tjaneczko**
We need to pass the authUrl to ghauth when working with GitHub enterprise, otherwise it'll try to use a token from github.com

### CODE REVIEW

**Comment by tjaneczko** [comment]
@ungoldman Fixed up GitHub enterprise auth and url detection and tested it on our GitHub enterprise server.  Everything works with these changes!

**Comment by ungoldman** [comment]
Looks good at first glance, will try to test it out in the next 24 hours!

**Comment by tjaneczko** [comment]
Awesome, thanks! Also, thanks for gh-release in the first place, it's an awesome tool that really helps to streamline our workflow

**Comment by tjaneczko** [comment]
@ungoldman Hate to bug you about this, but any chance you might be able to take another look at this PR sometime today or tomorrow?  Also wondering if you guys are looking for help maintaining this project, or with any of the other issues that are open on it. I was considering tackling #49 when I get some free time as that would be a really nice enhancement to gh-release 😄 Thanks!

**Comment by ungoldman** [comment]
📦 `3.2.3`

**Comment by jgravois** [comment]
fwiw, i tested this branch in GitHub enterprise and everything was 👍

**Comment by ungoldman** [comment]
Thanks @jgravois 🙏

**Comment by tjaneczko** [comment]
Awesome, thanks for reviewing @ungoldman and thanks for testing @jgravois !!  Accepted the invite, the collaborator guidelines all look kosher and I'm happy to help out with contributing and maintaining this project!

**Pull request merged**
